name: enguage # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Language Engine - NL programming in NL # 79 char long summary
description: |
  With the ability to create files by voice comes the ability to
  create the instructions to create files by voice, etc., etc., ... .
  Winner of the 2016 BCS Machine Intelligence Competition.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  enguage:
    command: bin/eng -d $SNAP_USER_DATA
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs: [home]

parts:
  enguage:
#    source: https://github.com/martinwheatman/enguage.git
#    plugin: make
    source: ./enguage.tgz
    plugin: dump
    stage-packages: [openjdk-11-jre]
